"""Case-pipeline pytest: EcThDiskCoupled (copper disk, electric-thermal coupled).

Note: this case uses a second-order (P2) mesh generated by COMSOL FreeTet
with default settings.  hellofem currently only supports P1 Lagrange bases,
so this case is skipped until second-order basis support is added.
"""
from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[3]
SCRIPTS = ROOT / "app" / "mpfem" / "scripts"
CASE = "EcThDiskCoupled"

_HAS_COMSOL = shutil.which("comsolbatch") is not None
_HAS_BUILD = (ROOT / "build" / "app" / ("mpfem_app.exe" if sys.platform == "win32" else "mpfem_app")).exists()

pytestmark = pytest.mark.skipif(
    not (_HAS_COMSOL and _HAS_BUILD),
    reason="needs COMSOL on PATH and a built mpfem_app")


def test_case_skipped():
    """Placeholder: EcThDiskCoupled requires P2 support (skip for now)."""
    pytest.skip("requires P2 basis support")
