// hellofem::app — parse a clean COMSOL Java model script into ModelScript
// SPDX-License-Identifier: MIT
#pragma once

#include "model_script.h"

#include <filesystem>
#include <string>

namespace hellofem::app {

    /// Parse a clean COMSOL Java model script (as produced by
    /// `model.save(path, "java")` and post-processed by the pipeline's
    /// clean step) into a `ModelScript`.
    ///
    /// The dialect handled is the subset generated by the autocomsol
    /// pipeline: `model.param().set`, `model.component().create`,
    /// `geom().create` (Block/Cylinder/Rectangle/Difference/Union/...),
    /// `material().create` + `selection().set` + `propertyGroup("def").set`,
    /// `physics().create` + `feature.create` + `feature.set` +
    /// `feature.selection().set`, `multiphysics().create` + `set`,
    /// `mesh().create` + `autoMeshSize`, `study().create` + feature,
    /// `result().export()`.
    ///
    /// Unsupported constructs raise `std::runtime_error` with a line number.
    ModelScript parse_model_java(const std::filesystem::path& filename);

} // namespace hellofem::app
